version: '3'

networks:
  laravel9vue3oauth2docker_network:

services:
  site:
    build:
      context: ./etc/dev
      dockerfile: nginx.dockerfile
    container_name: laravel9vue3oauth2docker_nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html:delegated
    depends_on:
      - php
      - mariadb
    networks:
      - laravel9vue3oauth2docker_network

  mariadb:
    image: mariadb:10.5.10
    container_name: laravel9vue3oauth2docker_mariadb
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./.db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel9vue3oauth2docker
      MYSQL_USER: laravel9vue3oauth2docker
      MYSQL_PASSWORD: laravel9vue3oauth2docker
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mariadb
    networks:
      - laravel9vue3oauth2docker_network

  php:
    build:
      context: ./etc/dev
      dockerfile: php.dockerfile
    container_name: laravel9vue3oauth2docker_php
    volumes:
      - ./:/var/www/html:delegated
      - ./etc/dev/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./etc/dev/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    ports:
      - "9000:9000"
    networks:
      - laravel9vue3oauth2docker_network

  composer:
    build:
      context: ./etc/dev
      dockerfile: composer.dockerfile
    container_name: laravel9vue3oauth2docker_composer
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    user: laravel
    networks:
      - laravel9vue3oauth2docker_network
    entrypoint: ['composer', '--ignore-platform-reqs']

  npm:
    image: node:18.7
    container_name: laravel9vue3oauth2docker_npm
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']

  artisan:
    build:
      context: ./etc/dev
      dockerfile: php.dockerfile
    container_name: laravel9vue3oauth2docker_artisan
    volumes:
      - ./:/var/www/html:delegated
    depends_on:
      - mariadb
#      - mysql
    working_dir: /var/www/html
    user: laravel
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - laravel9vue3oauth2docker_network
